---
- name: Apache web server Configuration playbook.
  hosts: all
  become: true
  tasks: 
    - name: installing apache web server
      yum:
        name: httpd
        state: latest

    - name: starting apche web server
      service:
        name: httpd
        state: started
        enabled: true

    - name: configuration of apche server
      template:
        src: /home/fahad/playbooks/index.j2
        dest: /var/www/html/index.html
        force: true

    - name: restarting apche service
      service:
        name: httpd
        state: restarted

    - name: configuring firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Reloading firewall 
      service:
        name: firewalld
        state: reloaded
...
